name: Deploy staging

on:
  pull_request:
    branches: ["staging"]
  push:
    branches: ["staging"]

concurrency:
  group: deploy-staging
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  pipeline:
    uses: ./.github/workflows/deploy-pipeline.yml
    with:
      environment: staging
      apps: '["administrador", "chequeras", "compras", "contable", "contratados", "guarani", "externo-consulta", "pagos"]'
      deploy: true
      deployRunner: staging
      deployScript: /data/docker/env-staging/deploy-tesoreria-frontend-staging.sh
    permissions:
      contents: read
      packages: write
    secrets: inherit
