name: Deploy develop

on:
  pull_request:
    branches: ["develop"]
  push:
    branches: ["develop"]

concurrency:
  group: deploy-develop
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  pipeline:
    uses: ./.github/workflows/deploy-pipeline.yml
    with:
      environment: develop
      apps: '["administrador", "chequeras", "compras", "contable", "contratados", "guarani", "externo-consulta", "pagos"]'
      deploy: true
      deployRunner: develop
      deployScript: /kibaig0ahNgashee/infraestructura/um/env-develop/deploy-tesoreria-frontend-develop.sh
    permissions:
      contents: read
      packages: write
    secrets: inherit
