name: Deploy main

on:
  push:
    branches: ["main"]

concurrency:
  group: deploy-main
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  pipeline:
    uses: ./.github/workflows/deploy-pipeline.yml
    with:
      environment: production
      apps: '["administrador", "chequeras", "compras", "contable", "contratados", "guarani", "externo-consulta", "pagos"]'
      deploy: false
      publishLatest: true
    permissions:
      contents: read
      packages: write
    secrets: inherit
